name: kardly
description: A K-Pop photocard collection and trading app for fans aged 14-30.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0

  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  animations: ^2.0.8
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
